### ISSUE TITLE
position_left will not take effect

### ISSUE THREAD

**Issue by WZY1999428** [marc2332/freya#1121]
When I was writing a slider component, I set the left side of the slider, but nothing changed.

[dependencies]
freya ={git = "https://github.com/marc2332/freya"}
dioxus = { version = "0.5", features = [
    "macro",
    "hooks",
], default-features = false }

```

use freya::prelude::*;
#[component]
pub fn Slider() -> Element {
    let mut is_mouse_down = use_signal(|| false);
    let (node_reference, node_size) = use_node();
    let mut left = use_signal(|| 0.0);
    let platform = use_platform();

    let onmouseleave = move |_| {
        platform.set_cursor(CursorIcon::default());
    };
    let onmouseenter = move |_| {
        platform.set_cursor(CursorIcon::Pointer);
    };
    rsx!(rect {
            width: "fill",
            height: "8",
            reference: node_reference,
            onmouseleave,
            onmouseenter,
            onmousedown:move|e|{
                let pointer=e.data.element_coordinates;
                left.set(pointer.x);
                is_mouse_down.set(true);
            },
            onglobalmousemove:move|e|{
                if *is_mouse_down.read(){
                    let el_pos = node_size.area.min();
                    let el_pos_max = node_size.area.max();
                    let pointer = e.data.element_coordinates;
                    let mut x = pointer.x - el_pos.x as f64;
                    let maxx = (el_pos_max.x - el_pos.x) as f64;
                    if x < 0.0 {
                        x = 0.0
                    } else if x > maxx {
                        x = maxx
                    }
                    left.set(x);
                }
            },
            onglobalclick:move|_|{
                is_mouse_down.set(false);
            },
            rect {
                background: "#535460",
                width:"fill",
                height:"3",
                corner_radius:"3",
                rect {
                    corner_radius:"3",
                    width:"{left}",
                    height:"fill",
                    background:"#ffd200"
                 }
             }
             rect {
                position:"absolute",
                position_top:"-3",
                // position_right:"{left}",
                position_left:"{left}",
                width:"10",
                height:"10",
                corner_radius:"5",
                background:"#ffd200"
              }
        })
}

```   

https://github.com/user-attachments/assets/c4e0ea4d-7a76-4fd2-8c54-46e76e5e72f4

**Comment by marc2332** [comment]
I see the bug, let me fix it

**Comment by marc2332** [comment]
Can you try https://github.com/marc2332/freya/pull/1122? It should fix it :)

**Comment by WZY1999428** [comment]
> Can you try [#1122](https://github.com/marc2332/freya/pull/1122)? It should fix it :)

It seems that it still doesn't work. I cleared the git cache and it didn't work.

**Comment by WZY1999428** [comment]
> > > > > Can you try [#1122](https://github.com/marc2332/freya/pull/1122)? It should fix it :)
> > > > 
> > > > 
> > > > It seems that it still doesn't work. I cleared the git cache and it didn't work.
> > > > 23-19-37.mp4
> > > 
> > > 
> > > You need to run `cargo update`
> > 
> > 
> > The result is still the same
> > 23-34-14.mp4
> 
> You are not using the PR I linked, you need to use it like this:
> 
> freya = { git = "https://github.com/marc2332/freya", branch = "fix/save-non-stacked-positions-until-position-is-swapped" }

Oh, I see! I didn’t know about this before. So it can be used now!

**Comment by WZY1999428** [comment]
> Cool! I will merge my PR asap and then you can switch to using
> 
> freya = { git = "https://github.com/marc2332/freya" }
> again

Got it! Thanks!
