### ISSUE TITLE
bug: Replaced elements from loaded from a batch in the same frame leads to a crash

### ISSUE THREAD

**Issue by ZeroX-DG** [marc2332/freya#602]
I encounter this error when I resize my app really quick. It doesn't happen on freya examples so I'm not sure what is causing this.

```
thread 'main' panicked at ~/.cargo/git/checkouts/freya-aa88117f1f713ee2/7b68806/crates/core/src/dom/mutations_writer.rs:46:60:
called `Option::unwrap()` on a `None` value
thread 'main' panicked at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/macos/app_state.rs:387:33:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
```

**Comment by marc2332** [comment]
Looks like some kind of edge case I missed, will look into it asap!

**Comment by marc2332** [comment]
hey, I can't reproduce it, so I pushed a branch with some logs which could help me debug it -> https://github.com/marc2332/freya/tree/fix/mutations-writer-error

Could you run your app with it and share me the logs once it crashes?

**Comment by marc2332** [comment]
Would also appreciate it if you could narrow it down in your app

**Comment by ZeroX-DG** [comment]
Hey, here's the resulting log:

```
EId(58.0) Element(ElementNode { tag: Rect, attributes: {Layer: Text("-10"), Width: Text("8.4"), Background: Text("rgb(165, 172, 186)"), PositionTop: Text("0"), Height: Text("18"), Color: Text("rgb(17, 21, 28)"), PositionLeft: Text("42"), Position: Text("absolute")}, listeners: {} }) 8
EId(59.0) Element(ElementNode { tag: Rect, attributes: {}, listeners: {} }) 9
EId(60.0) Element(ElementNode { tag: Label, attributes: {}, listeners: {} }) 10
EId(60.1) Element(ElementNode { tag: Rect, attributes: {Layer: Text("-10"), Width: Text("8.4"), Background: Text("rgb(165, 172, 186)"), PositionTop: Text("0"), Height: Text("18"), Color: Text("rgb(17, 21, 28)"), PositionLeft: Text("8.4"), Position: Text("absolute")}, listeners: {} }) 8
EId(59.1) Element(ElementNode { tag: Rect, attributes: {}, listeners: {} }) 9
EId(58.1) Element(ElementNode { tag: Label, attributes: {}, listeners: {} }) 10
EId(99.1) Element(ElementNode { tag: Rect, attributes: {Layer: Text("-10"), Width: Text("8.4"), Background: Text("rgb(165, 172, 186)"), PositionTop: Text("0"), Height: Text("18"), Color: Text("rgb(17, 21, 28)"), PositionLeft: Text("0"), Position: Text("absolute")}, listeners: {} }) 8
EId(183.0) Element(ElementNode { tag: Rect, attributes: {}, listeners: {} }) 9
EId(184.0) Element(ElementNode { tag: Label, attributes: {}, listeners: {} }) 10
EId(195.0) Element(ElementNode { tag: Rect, attributes: {Layer: Text("-10"), Width: Text("8.4"), Background: Text("rgb(165, 172, 186)"), PositionTop: Text("0"), Height: Text("18"), Color: Text("rgb(17, 21, 28)"), PositionLeft: Text("327.59998"), Position: Text("absolute")}, listeners: {} }) 8
EId(196.0) Element(ElementNode { tag: Rect, attributes: {}, listeners: {} }) 9
EId(197.0) Element(ElementNode { tag: Label, attributes: {}, listeners: {} }) 10
EId(58.3) Element(ElementNode { tag: Rect, attributes: {Layer: Text("-10"), Width: Text("8.4"), Background: Text("rgb(165, 172, 186)"), PositionTop: Text("0"), Height: Text("18"), Color: Text("rgb(17, 21, 28)"), PositionLeft: Text("42"), Position: Text("absolute")}, listeners: {} }) 8
EId(84.2) Element(ElementNode { tag: Rect, attributes: {}, listeners: {} }) 9
EId(60.3) Element(ElementNode { tag: Label, attributes: {}, listeners: {} }) 10
EId(193.1) Element(ElementNode { tag: Rect, attributes: {Layer: Text("-10"), Width: Text("8.4"), Background: Text("rgb(165, 172, 186)"), PositionTop: Text("0"), Height: Text("18"), Color: Text("rgb(17, 21, 28)"), PositionLeft: Text("16.8"), Position: Text("absolute")}, listeners: {} }) 8
EId(192.1) Element(ElementNode { tag: Rect, attributes: {}, listeners: {} }) 9
EId(191.1) Element(ElementNode { tag: Label, attributes: {}, listeners: {} }) 10
EId(59.4) Element(ElementNode { tag: Rect, attributes: {Layer: Text("-10"), Width: Text("8.4"), Background: Text("rgb(165, 172, 186)"), PositionTop: Text("0"), Height: Text("18"), Color: Text("rgb(17, 21, 28)"), PositionLeft: Text("16.8"), Position: Text("absolute")}, listeners: {} }) 8
thread 'main' panicked at ~/.cargo/git/checkouts/freya-aa88117f1f713ee2/e5c73a2/crates/core/src/dom/mutations_writer.rs:48:60:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/macos/app_state.rs:387:33:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
```

It seems like it was caused by a custom `rect` that I created to represent the cursor in my terminal emulator:

https://github.com/ZeroX-DG/raven/blob/22685396b27e589b6d7bb3b9dcd4099ae84b2544/src/components/content_area.rs#L84-L99

I tried removing the `layer` property but it still crash the app with the same error. I'll try finding out more info.

**Comment by ZeroX-DG** [comment]
Very strange. The node exists when we get it out using `native_writer.rdom.get` but disappear when we use the realdom tree to access it. Perhaps there's a race condition somewhere....could it be shipyard bug? 😄

**Comment by marc2332** [comment]
> Very strange. The node exists when we get it out using `native_writer.rdom.get` but disappear when we use the realdom tree to access it. Perhaps there's a race condition somewhere...

I would very surprised if it was a race condition, I think it's just some weird case or something, because I have never got that error, not even on Valin, which is quite complex

**Comment by ZeroX-DG** [comment]
Here's a video of my replicating the bug if it helpful:

https://github.com/marc2332/freya/assets/12984316/263bbf4c-501f-4f94-8219-8bcdcf1642d5

**Comment by marc2332** [comment]
I wonder if you might be calling some blocking code that could be making the realdom act weird, https://github.com/ZeroX-DG/raven/blob/22685396b27e589b6d7bb3b9dcd4099ae84b2544/src/components/content_area.rs#L49

Could you try commenting tha code?

**Comment by marc2332** [comment]
If that's the issue I think you could try running the pty in a secondary thread and uses mpsc channels to communicate, so it doesn't block the main thread in any way

**Comment by marc2332** [comment]
I just pushed some changes to the branch, could try it @ZeroX-DG ?

**Comment by marc2332** [comment]
If that still fails, I have another idea too

**Comment by ZeroX-DG** [comment]
Ok commenting out the `resize` definitely helps. But without commenting it, the app still crash with your latest changes on the branch:

```
EId(99.13) Element(ElementNode { tag: Rect, attributes: {Layer: Text("-10"), Width: Text("8.4"), Background: Text("rgb(165, 172, 186)"), PositionTop: Text("0"), Height: Text("18"), Color: Text("rgb(17, 21, 28)"), PositionLeft: Text("42"), Position: Text("absolute")}, listeners: {} }) 8
EId(191.12) Element(ElementNode { tag: Rect, attributes: {}, listeners: {} }) 9
EId(70.10) Element(ElementNode { tag: Label, attributes: {}, listeners: {} }) 10
Removing...
Removing...
Removing...
EId(65.13) Element(ElementNode { tag: Rect, attributes: {Layer: Text("-10"), Width: Text("8.4"), Background: Text("rgb(165, 172, 186)"), PositionTop: Text("0"), Height: Text("18"), Color: Text("rgb(17, 21, 28)"), PositionLeft: Text("8.4"), Position: Text("absolute")}, listeners: {} }) 8
EId(187.11) Element(ElementNode { tag: Rect, attributes: {}, listeners: {} }) 9
EId(64.14) Element(ElementNode { tag: Label, attributes: {}, listeners: {} }) 10
Removing...
Removing...
Removing...
Removing...
Removing...
Removing...
EId(60.18) Element(ElementNode { tag: Rect, attributes: {Layer: Text("-10"), Width: Text("8.4"), Background: Text("rgb(165, 172, 186)"), PositionTop: Text("0"), Height: Text("18"), Color: Text("rgb(17, 21, 28)"), PositionLeft: Text("8.4"), Position: Text("absolute")}, listeners: {} }) 8
thread 'main' panicked at /Users/viethung/.cargo/git/checkouts/freya-aa88117f1f713ee2/f62e9d5/crates/core/src/dom/mutations_writer.rs:49:60:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /Users/viethung/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/macos/app_state.rs:387:33:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
```

**Comment by marc2332** [comment]
Just pushed my other idea, can you try it @ZeroX-DG ?

**Comment by ZeroX-DG** [comment]
Having the resize run in the separate thread seems to fix it as well!

![Screenshot 2024-05-04 at 10 29 17 PM](https://github.com/marc2332/freya/assets/12984316/abcf03e5-8615-4ae2-a6cd-5af9d16dea72)

**Comment by marc2332** [comment]
> Having the resize run in the separate thread seems to fix it as well!
> 
> ![Screenshot 2024-05-04 at 10 29 17 PM](https://private-user-images.githubusercontent.com/12984316/327941699-abcf03e5-8615-4ae2-a6cd-5af9d16dea72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MTg5ODMsIm5iZiI6MTcxNDgxODY4MywicGF0aCI6Ii8xMjk4NDMxNi8zMjc5NDE2OTktYWJjZjAzZTUtODYxNS00YWUyLWE2Y2QtNWFmOWQxNmRlYTcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDEwMzEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMThiMTI3YWRjNTdjZGE5ZjliNmEwNTU1NDI3N2E0NThiNzRmNDM0NjQyNTRlMjI1MGU4MmUwNzFmYzA3YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h_6oviK52Zw5T3-HnBxLUaSnAmnDdqzZt0niPuEI6DE)

Nice, although you should probably organize it another way so you don't spawn a thread every time the app gets resized haha, mpsc would do fine here

**Comment by ZeroX-DG** [comment]
> Just pushed my other idea

Yeah that still crash unfortunately 😄

**Comment by marc2332** [comment]
Oh wait, hold on a sec

**Comment by marc2332** [comment]
https://github.com/ZeroX-DG/raven/blob/22685396b27e589b6d7bb3b9dcd4099ae84b2544/src/components/content_area.rs#L76

You are missing the `key`:

```rs
 rect {
    key: "{line_index}",
    padding: "{line_spacing} 0",
    paragraph {
```

Not specifying it could lead to DOM inconsistencies

**Comment by ZeroX-DG** [comment]
> Nice, although you should probably organize it another way so you don't spawn a thread every time the app gets resized haha, mpsc would do fine here

Yeah for sure haha. This make me wish we have something like a `use_separate_thread` hook haha.

**Comment by ZeroX-DG** [comment]
> Not specifying it could lead to DOM inconsistencies, I wonder if that's related

Hmmmm could be..........I'll try specifying a key.

**Comment by ZeroX-DG** [comment]
Nope still crash.

**Comment by marc2332** [comment]
Leave the key anyway, I guess running it in another thread is the way to go then. I don't really know if this is a bug or more like an issue caused by "wrong use" of the library (blocking the main thread unexpectedly)?

Having a `use_thread` hook for [Dioxus SDK](https://github.com/DioxusLabs/sdk) could be cool

**Comment by marc2332** [comment]
You could also try using async tasks and a async Mutex instead of std's Mutex

**Comment by ZeroX-DG** [comment]
> You could also try using async tasks and a async Mutex instead of std's Mutex

Oh are you talking about this crate: https://docs.rs/async-mutex/latest/async_mutex/ ? Or is it something built in?

**Comment by marc2332** [comment]
> > You could also try using async tasks and a async Mutex instead of std's Mutex
> 
> Oh are you talking about this crate: https://docs.rs/async-mutex/latest/async_mutex/ ? Or is it something built in?

I was actually thinking about tokio's Mutex

**Comment by marc2332** [comment]
https://docs.rs/tokio/latest/tokio/sync/struct.Mutex.html

**Comment by ZeroX-DG** [comment]
> I don't really know if this is a bug or more like an issue caused by "wrong use" of the library (blocking the main thread unexpectedly)?

Yeah I agree. It's probably not a bug. More of a user error. Still, it's a chance for improvement. Maybe we can somehow let users know when their code is valid to run on the main thread & when it's not?

**Comment by ZeroX-DG** [comment]
> https://docs.rs/tokio/latest/tokio/sync/struct.Mutex.html

Oh cool. I've never used it before. Coming from JavaScript land, these multi-threading stuff is pretty new to me haha. I'll give it a try!

**Comment by marc2332** [comment]
> > I don't really know if this is a bug or more like an issue caused by "wrong use" of the library (blocking the main thread unexpectedly)?
> 
> Yeah I agree. It's probably not a bug. More of a user error. Still, it's a chance for improvement. Maybe we can somehow let users know when their code is valid to run on the main thread & when it's not?

A note on the docs would be very nice indeed, most frameworks let you know that the UI thread should not be blocked and that expensive calculations should be done in secondary threads or similar

**Comment by marc2332** [comment]
This is indeed a bug @ZeroX-DG in Freya. I was assuming wrong.

**Comment by marc2332** [comment]
Opened a fix in https://github.com/marc2332/freya/pull/744 @ZeroX-DG
